"""Create user table and add owner_id to focus_sessions

Revision ID: a818812802e0
Revises: 
Create Date: 2025-12-27 22:23:37.294876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a818812802e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'flag_aktif',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('focus_sessions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('focus_sessions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_focus_sessions_id'), 'focus_sessions', ['id'], unique=False)
    op.create_foreign_key(None, 'focus_sessions', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'focus_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_focus_sessions_id'), table_name='focus_sessions')
    op.alter_column('focus_sessions', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('focus_sessions', 'owner_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'flag_aktif',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
